import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';

// Noto Sans JP（英語 & 日本語 共通フォント）
const notoSansJP = Noto_Sans_JP({ subsets: ['latin'], weight: ['500', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={`${notoSansJP.className} text-custom-black bg-custom-light-gray`}>
        {children}
      </body>
    </html>
  );
}